services:
  pump_simulation:
    build: .
    container_name: pump_simulator_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./frontend:/app/frontend
    command: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  pump_test:
    build: .
    container_name: pump_test_runner
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: ["pytest", "tests/test_pump.py", "-v"]
    profiles:
      - testing