export const translations = {
    es: {
        titulo_app: "SIMULADOR DE BOMBEO INDUSTRIAL",
        btn_formulas_custom: "Fórmulas Custom",
        preset_cu: "Caso Base: Concentrado Cu",
        preset_agua: "Caso 2: Agua de Proceso",
        preset_relave: "Caso 3: Relaves Espesados",
        param_entrada: "Parámetros de Entrada",
        prop_fluido: "Propiedades del Fluido",
        modo_fluido: "Modo Fluido",
        modo_pulpa: "Concentración (Pulpa)",
        modo_agua: "Agua Pura / Directo",
        label_cp: "Concentración Sólidos (Cp)",
        label_ge: "GE Sólidos",
        label_densidad: "Densidad (kg/m³)",
        label_visc: "Visc. Cinemática (m²/s)",
        label_presion_v: "Presión Vapor (mca)",
        label_espuma: "Factor Espuma (Cs)",
        datos_sistema: "Datos del Sistema y Ciclo",
        label_caudal: "Caudal Diseño (m³/h)",
        label_cota_e: "Cota Estática Total (m)",
        label_presion_dif: "P. Inicial Filtro (mca)",
        label_presion_dif_final: "P. Final Filtro (mca)",
        label_altura_s: "Altura Succión (z_suc m)",
        label_presion_a: "Presión Atm. (mca)",
        label_eficiencia: "Rend. Bomba (%)",
        label_npshr: "NPSHr Fabricante (mcl)",
        datos_motor: "Eficiencias, ER y Holguras",
        label_ef_motor: "Rend. Motor (%)",
        label_er: "Rend. Sólidos (ER Cave)",
        label_f_seguridad: "F.S. Potencia",
        curva_bomba_titulo: "Curva H-Q del Fabricante",
        metodo_ingreso: "Método de Ingreso de Curva",
        opt_sin_curva: "No simular curva de bomba (Solo Sistema)",
        opt_3_puntos: "3 Puntos de Catálogo (Shut-off, BEP, Máx)",
        opt_coef: "Coeficientes Directos Parábola (A Q² + B Q + C)",
        lbl_shutoff: "Shut-off H (m)",
        lbl_qbep: "Q BEP (m³/h)",
        lbl_hbep: "H BEP (m)",
        lbl_qmax: "Q Máx (m³/h)",
        lbl_hmax: "H Máx (m)",
        lbl_coef_a: "Coef. A (Q²)",
        lbl_coef_b: "Coef. B (Q)",
        lbl_coef_c: "Coef. C (Shut)",
        datos_tuberias: "Geometría de Tuberías",
        label_material: "Material de Línea",
        label_rugosidad: "Rugosidad Abs. (m)",
        tramo_suc: "Tramo Succión",
        tramo_des: "Tramo Descarga",
        label_l: "Long (m)",
        datos_transitorios: "Factores Cave, Durand y Transitorios",
        label_celeridad: "Celeridad (m/s)",
        label_t_cierre: "Tiempo de Cierre de Válvulas (s)",
        btn_calcular: "Calcular Sistema",
        kpi_tdh: "TDH Total",
        kpi_potencia: "Potencia Requerida",
        kpi_cavitacion: "Estado de Cavitación",
        reporte_titulo: "Matriz de Reporte Técnico",
        btn_exportar: "Exportar CSV",
        btn_imprimir: "Imprimir PDF",
        row_densidad: "Densidad de Operación:",
        row_ge_fluido: "Gravedad Específica (Sm):",
        row_v_suc: "Velocidad Succión:",
        row_v_des: "Velocidad Descarga:",
        row_cave: "H Equivalente Agua (Cave):",
        row_durand: "Vel. Crítica Durand (VL):",
        row_sumergencia: "Sumergencia Mínima Sentina:",
        row_rec_diametro: "Asesor Diámetro Óptimo:",
        row_ariete: "Análisis Golpe de Ariete:",
        curva_titulo: "Ciclo Completo Presión Filtro (Q vs TDH)",
        modal_titulo: "Suite de Configuración de Ecuaciones Dinámicas",
        btn_restaurar: "Restaurar Valores",
        btn_guardar: "Guardar y Compilar Suite",
        status_seguro: "SEGURO",
        status_alerta: "ALERTA CAVITACIÓN",
        ariete_lento: "Michaud (Cierre Lento)",
        ariete_rapido: "Allievi (Cierre Rápido)",
        ariete_mca: "mca",
        metodo_label: "Método",
        solo_pulpa: "N/A (Solo Pulpa)",
        vel_alta: "Alerta: Velocidad Alta (Reducir diámetro)",
        vel_baja: "Alerta: Riesgo Sedimentación (Aumentar diámetro)",
        vel_ok: "OK — Cumple rango admisorio corporativo",
        chart_ciclo_ini: "Ciclo Inicial (Filtro Vacío)",
        chart_ciclo_fin: "Fin de Ciclo (Filtro Lleno)",
        chart_punto_consigna: "Punto Consigna Ingresado",
        chart_curva_bomba: "Curva de la Bomba (Fabricante)",
        chart_cruce_ini: "Cruce Operativo Inicial Real",
        chart_cruce_fin: "Cruce Operativo Final Real",
        
        // Missing keys added
        transporte_ok: "OK — Velocidad segura",
        transporte_alerta: "Alerta Sedimentación",
        alert_csv_error: "Ejecute un cálculo previo.",
        header_variables: "Variables: ",
        header_return: "Retorno Obligatorio: ",
        pipe_steel: "Acero Comercial",
        pipe_hdpe: "HDPE / PEAD",
        pipe_pvc: "PVC Industrial",
        lbl_d_int: "D_int (m)",
        lbl_k_acc: "Σ K acc",
        modal_label_friccion: "1. Factor de Fricción Turbulento (f)",
        modal_label_durand: "2. Velocidad Límite de Sedimentación (VL)",
        modal_label_viscosidad: "3. Reología: Viscosidad Aparente Pulpa (μm)",
        modal_label_celeridad: "4. Transitorios: Celeridad del Golpe de Ariete (a)",
        modal_label_cave: "5. Criterio Cave: Reducción de Altura y Eficiencia",
        tpl_friccion_haaland: "Modelo Base: Haaland (Rápido)",
        tpl_friccion_laminar: "Caso Borde: Flujo Puramente Laminar (64/Re)",
        tpl_user_custom: "Mi Fórmula Personalizada",
        tpl_durand_std: "Modelo Base: Durand Standard",
        tpl_durand_mod: "Variante: Durand Penalizado por Concentración",
        tpl_viscosidad_thomas: "Fórmula Empírica: Thomas (Pulpas Pesadas)",
        tpl_viscosidad_einstein: "Fórmula Base: Einstein-Roscoe",
        tpl_celeridad_korteweg: "Ecuación Teórica: Korteweg & Joukowsky (Elástica)",
        tpl_celeridad_fijo: "Valor Fijo de Resguardo Industrial",
        tpl_cave_std: "Criterio Base: Retorno Estático de Catálogo",
        tpl_cave_log: "Variante: Ajuste Logarítmico HI",
        btn_save_custom: "Guardar Custom"
    },
    en: {
        titulo_app: "INDUSTRIAL PUMPING SIMULATOR",
        btn_formulas_custom: "Custom Formulas",
        preset_cu: "Base Case: Cu Concentrate",
        preset_agua: "Case 2: Process Water",
        preset_relave: "Case 3: Thickened Tailings",
        param_entrada: "Input Parameters",
        prop_fluido: "Fluid Properties",
        modo_fluido: "Fluid Mode",
        modo_pulpa: "Concentration (Slurry)",
        modo_agua: "Pure Water / Direct",
        label_cp: "Solids Concentration (Cp)",
        label_ge: "Solids SG",
        label_densidad: "Density (kg/m³)",
        label_visc: "Kinematic Visc. (m²/s)",
        label_presion_v: "Vapor Pressure (wcm)",
        label_espuma: "Froth Factor (Cs)",
        datos_sistema: "System & Cycle Data",
        label_caudal: "Design Flow (m³/h)",
        label_cota_e: "Total Static Head (m)",
        label_presion_dif: "Initial Filter P. (wcm)",
        label_presion_dif_final: "Final Filter P. (wcm)",
        label_altura_s: "Suction Lift (z_suc m)",
        label_presion_a: "Atm. Pressure (wcm)",
        label_eficiencia: "Pump Eff. (%)",
        label_npshr: "Manufacturer NPSHr (wcl)",
        datos_motor: "Efficiency, ER & Safety Factors",
        label_ef_motor: "Motor Eff. (%)",
        label_er: "Solids Correction (ER Cave)",
        label_f_seguridad: "Power S.F.",
        curva_bomba_titulo: "Manufacturer H-Q Curve",
        metodo_ingreso: "Curve Input Method",
        opt_sin_curva: "Do not simulate pump curve (System Only)",
        opt_3_puntos: "3 Catalog Points (Shut-off, BEP, Max)",
        opt_coef: "Direct Parabola Coefficients (A Q² + B Q + C)",
        lbl_shutoff: "Shut-off H (m)",
        lbl_qbep: "Q BEP (m³/h)",
        lbl_hbep: "H BEP (m)",
        lbl_qmax: "Max Q (m³/h)",
        lbl_hmax: "Max H (m)",
        lbl_coef_a: "Coef. A (Q²)",
        lbl_coef_b: "Coef. B (Q)",
        lbl_coef_c: "Coef. C (Shut)",
        datos_tuberias: "Pipe Geometry",
        label_material: "Line Material",
        label_rugosidad: "Roughness Abs. (m)",
        tramo_suc: "Suction Pipe",
        tramo_des: "Discharge Pipe",
        label_l: "Length (m)",
        datos_transitorios: "Cave, Durand & Transients Factors",
        label_celeridad: "Wave Speed (m/s)",
        label_t_cierre: "Valve Closure Time (s)",
        btn_calcular: "Calculate System",
        kpi_tdh: "Total TDH",
        kpi_potencia: "Required Power",
        kpi_cavitacion: "Cavitation Status",
        reporte_titulo: "Technical Report Matrix",
        btn_exportar: "Export CSV",
        btn_imprimir: "Print PDF",
        row_densidad: "Operating Density:",
        row_ge_fluido: "Specific Gravity (Sm):",
        row_v_suc: "Suction Velocity:",
        row_v_des: "Discharge Velocity:",
        row_cave: "Water Equivalent Head (Cave):",
        row_durand: "Durand Critical Vel. (VL):",
        row_sumergencia: "Critical Suction Submergence:",
        row_rec_diametro: "Optimum Diameter Advisor:",
        row_ariete: "Water Hammer Analysis:",
        curva_titulo: "Full Filter Pressure Cycle (Q vs TDH)",
        modal_titulo: "Dynamic Equations Configuration Suite",
        btn_restaurar: "Restore Values",
        btn_guardar: "Save & Compile Suite",
        status_seguro: "SAFE",
        status_alerta: "CAVITATION ALERT",
        ariete_lento: "Michaud (Slow Closure)",
        ariete_rapido: "Allievi (Fast Closure)",
        ariete_mca: "w.c.m.",
        metodo_label: "Method",
        solo_pulpa: "N/A (Slurry Only)",
        vel_alta: "Alert: High Velocity (Reduce pipe diameter)",
        vel_baja: "Alert: Sedimentation Risk (Increase pipe diameter)",
        vel_ok: "OK — Conforms to corporate allowed bounds",
        chart_ciclo_ini: "Initial Cycle (Empty Filter)",
        chart_ciclo_fin: "End Cycle (Full Filter)",
        chart_punto_consigna: "Input Setpoint",
        chart_curva_bomba: "Pump Curve (Manufacturer)",
        chart_cruce_ini: "Real Initial Operating Point",
        chart_cruce_fin: "Real Final Operating Point",
        
        // Missing keys added
        transporte_ok: "OK — Safe Velocity",
        transporte_alerta: "Sedimentation Alert",
        alert_csv_error: "Please run a calculation first.",
        header_variables: "Variables: ",
        header_return: "Required Return: ",
        pipe_steel: "Commercial Steel",
        pipe_hdpe: "HDPE / PEAD",
        pipe_pvc: "Industrial PVC",
        lbl_d_int: "Inner D. (m)",
        lbl_k_acc: "Σ K acc",
        modal_label_friccion: "1. Turbulent Friction Factor (f)",
        modal_label_durand: "2. Limit Deposition Velocity (VL)",
        modal_label_viscosidad: "3. Rheology: Slurry Apparent Viscosity (μm)",
        modal_label_celeridad: "4. Transients: Water Hammer Wave Speed (a)",
        modal_label_cave: "5. Cave Criterion: Head & Efficiency De-rating",
        tpl_friccion_haaland: "Base Model: Haaland (Fast)",
        tpl_friccion_laminar: "Edge Case: Purely Laminar Flow (64/Re)",
        tpl_user_custom: "My Custom Formula",
        tpl_durand_std: "Base Model: Durand Standard",
        tpl_durand_mod: "Variant: Durand Adjusted by Concentration",
        tpl_viscosidad_thomas: "Empirical Formula: Thomas (Heavy Slurries)",
        tpl_viscosidad_einstein: "Base Formula: Einstein-Roscoe",
        tpl_celeridad_korteweg: "Theoretical Equation: Korteweg & Joukowsky (Elastic)",
        tpl_celeridad_fijo: "Fixed Industrial Safeguard Value",
        tpl_cave_std: "Base Criterion: Static Catalog Return",
        tpl_cave_log: "Variant: Logarithmic HI Adjustment",
        btn_save_custom: "Save Custom"
    }
};
